version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  customer-service:
    image: ${REGISTRY:-service-one}/customer-service.api:${PLATFORM:-windows}-${TAG:-latest}
    depends_on:
      - "BeSmart_db"
    container_name: BeSmart-container
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Project/Presentation/BeSmart.WebApi/Dockerfile
    environment:
      - ConnectionString=host=locallhost;port=5435;database=BeSmart2;username=postgres;password=dash844a;Pooling=true;
    networks:
      - dev

  customer_db:
    image: postgres:latest
    container_name: BeSmart_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dash844a
      - POSTGRES_DB=BeSmart2
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev
      
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - dev

volumes:
  customer_data: