version: '3.4'

services:
  besmart.webapi:
    image: ${DOCKER_REGISTRY-}besmartwebapi
    container_name: besmart.webapi.container
    build:
      context: .
      dockerfile: BeSmart.WebApi/Dockerfile

  postgres.db:
    image: postgres:latest
    container_name: postgres.db.container